--------------------------------------------------------
--  File created - Wednesday-July-08-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASISTENCIA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ASISTENCIA" 
   (	"ASISTENCIA_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLEADO_ID" NUMBER, 
	"FECHA" DATE, 
	"HORA_ENTRADA" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"HORA_SALIDA" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"OBSERVACION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CARGO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CARGO" 
   (	"CARGO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_CARGO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SUELDO_BASE" NUMBER(10,2)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CATEGORIA" 
   (	"CATEGORIA_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_CATEGORIA" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPCION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "ADMIN"."CATEGORIA" TO "ROL_CAJERO_ORA";
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EMPLEADO" 
   (	"EMPLEADO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRES" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"APELLIDOS" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"DNI" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"CARGO_ID" NUMBER, 
	"SUCURSAL_ID" NUMBER, 
	"FECHA_CONTRATACION" DATE, 
	"ESTADO" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'ACTIVO'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT ALTER ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT DELETE ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT INSERT ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT SELECT ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT UPDATE ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT READ ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT ON COMMIT REFRESH ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT QUERY REWRITE ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT DEBUG ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT FLASHBACK ON "ADMIN"."EMPLEADO" TO "ROL_ADMIN_ORA";
  GRANT SELECT ON "ADMIN"."EMPLEADO" TO "ROL_SUPERVISOR_ORA";
--------------------------------------------------------
--  DDL for Table HORARIO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."HORARIO" 
   (	"HORARIO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLEADO_ID" NUMBER, 
	"DIA_SEMANA" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"HORA_INICIO" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"HORA_FIN" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table INSUMO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."INSUMO" 
   (	"INSUMO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_INSUMO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UNIDAD_MEDIDA" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"STOCK_ACTUAL" NUMBER(10,2) DEFAULT 0, 
	"STOCK_MINIMO" NUMBER(10,2) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT ALTER ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT DELETE ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT INSERT ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT SELECT ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT UPDATE ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT READ ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT ON COMMIT REFRESH ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT QUERY REWRITE ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT DEBUG ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT FLASHBACK ON "ADMIN"."INSUMO" TO "ROL_ADMIN_ORA";
  GRANT SELECT ON "ADMIN"."INSUMO" TO "ROL_SUPERVISOR_ORA";
  GRANT SELECT ON "ADMIN"."INSUMO" TO "ROL_COCINERO_ORA";
--------------------------------------------------------
--  DDL for Table MOVIMIENTO_INVENTARIO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" 
   (	"MOVIMIENTO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"INSUMO_ID" NUMBER, 
	"SUCURSAL_ID" NUMBER, 
	"TIPO_MOVIMIENTO" VARCHAR2(8 BYTE) COLLATE "USING_NLS_COMP", 
	"CANTIDAD" NUMBER(10,2), 
	"FECHA_MOVIMIENTO" DATE DEFAULT SYSDATE, 
	"MOTIVO" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
  GRANT SELECT ON "ADMIN"."MOVIMIENTO_INVENTARIO" TO "ROL_SUPERVISOR_ORA";
  GRANT INSERT ON "ADMIN"."MOVIMIENTO_INVENTARIO" TO "ROL_COCINERO_ORA";
  GRANT UPDATE ON "ADMIN"."MOVIMIENTO_INVENTARIO" TO "ROL_COCINERO_ORA";
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PRODUCTO" 
   (	"PRODUCTO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_PRODUCTO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORIA_ID" NUMBER, 
	"PRECIO" NUMBER(8,2), 
	"DISPONIBLE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'S'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT ALTER ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT DELETE ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT INSERT ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT SELECT ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT UPDATE ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT READ ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT ON COMMIT REFRESH ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT QUERY REWRITE ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT DEBUG ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT FLASHBACK ON "ADMIN"."PRODUCTO" TO "ROL_ADMIN_ORA";
  GRANT SELECT ON "ADMIN"."PRODUCTO" TO "ROL_SUPERVISOR_ORA";
  GRANT SELECT ON "ADMIN"."PRODUCTO" TO "ROL_CAJERO_ORA";
  GRANT SELECT ON "ADMIN"."PRODUCTO" TO "ROL_COCINERO_ORA";
--------------------------------------------------------
--  DDL for Table PRODUCTO_INSUMO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PRODUCTO_INSUMO" 
   (	"PRODUCTO_ID" NUMBER, 
	"INSUMO_ID" NUMBER, 
	"CANTIDAD_REQUERIDA" NUMBER(8,2)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT SELECT ON "ADMIN"."PRODUCTO_INSUMO" TO "ROL_COCINERO_ORA";
--------------------------------------------------------
--  DDL for Table SUCURSAL
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SUCURSAL" 
   (	"SUCURSAL_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DIRECCION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CIUDAD" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"TELEFONO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  GRANT ALTER ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT DELETE ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT INSERT ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT SELECT ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT UPDATE ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT READ ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT ON COMMIT REFRESH ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT QUERY REWRITE ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT DEBUG ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT FLASHBACK ON "ADMIN"."SUCURSAL" TO "ROL_ADMIN_ORA";
  GRANT SELECT ON "ADMIN"."SUCURSAL" TO "ROL_SUPERVISOR_ORA";
REM INSERTING into ADMIN.ASISTENCIA
SET DEFINE OFF;
REM INSERTING into ADMIN.CARGO
SET DEFINE OFF;
Insert into ADMIN.CARGO (CARGO_ID,NOMBRE_CARGO,SUELDO_BASE) values (1,'Administrador',3500);
Insert into ADMIN.CARGO (CARGO_ID,NOMBRE_CARGO,SUELDO_BASE) values (2,'Supervisor',2800);
Insert into ADMIN.CARGO (CARGO_ID,NOMBRE_CARGO,SUELDO_BASE) values (3,'Cajero',1500);
Insert into ADMIN.CARGO (CARGO_ID,NOMBRE_CARGO,SUELDO_BASE) values (4,'Cocinero',1800);
REM INSERTING into ADMIN.CATEGORIA
SET DEFINE OFF;
Insert into ADMIN.CATEGORIA (CATEGORIA_ID,NOMBRE_CATEGORIA,DESCRIPCION) values (1,'Entrada','Platos de entrada');
Insert into ADMIN.CATEGORIA (CATEGORIA_ID,NOMBRE_CATEGORIA,DESCRIPCION) values (2,'Fondo','Platos de fondo');
Insert into ADMIN.CATEGORIA (CATEGORIA_ID,NOMBRE_CATEGORIA,DESCRIPCION) values (3,'Bebida','Bebidas frias y calientes');
REM INSERTING into ADMIN.EMPLEADO
SET DEFINE OFF;
Insert into ADMIN.EMPLEADO (EMPLEADO_ID,NOMBRES,APELLIDOS,DNI,CARGO_ID,SUCURSAL_ID,FECHA_CONTRATACION,ESTADO) values (1,'Luis','Ramirez','70001122',1,1,to_date('01-MAR-24','DD-MON-RR'),'ACTIVO');
Insert into ADMIN.EMPLEADO (EMPLEADO_ID,NOMBRES,APELLIDOS,DNI,CARGO_ID,SUCURSAL_ID,FECHA_CONTRATACION,ESTADO) values (2,'Maria','Castillo','70002233',3,1,to_date('15-MAY-24','DD-MON-RR'),'ACTIVO');
Insert into ADMIN.EMPLEADO (EMPLEADO_ID,NOMBRES,APELLIDOS,DNI,CARGO_ID,SUCURSAL_ID,FECHA_CONTRATACION,ESTADO) values (3,'Jorge','Salas','70003344',4,1,to_date('01-JUN-24','DD-MON-RR'),'ACTIVO');
Insert into ADMIN.EMPLEADO (EMPLEADO_ID,NOMBRES,APELLIDOS,DNI,CARGO_ID,SUCURSAL_ID,FECHA_CONTRATACION,ESTADO) values (4,'Paola','Reyes','70004455',3,2,to_date('10-JUL-24','DD-MON-RR'),'ACTIVO');
REM INSERTING into ADMIN.HORARIO
SET DEFINE OFF;
REM INSERTING into ADMIN.INSUMO
SET DEFINE OFF;
Insert into ADMIN.INSUMO (INSUMO_ID,NOMBRE_INSUMO,UNIDAD_MEDIDA,STOCK_ACTUAL,STOCK_MINIMO) values (1,'Papa','kg',50,10);
Insert into ADMIN.INSUMO (INSUMO_ID,NOMBRE_INSUMO,UNIDAD_MEDIDA,STOCK_ACTUAL,STOCK_MINIMO) values (2,'Carne de Res','kg',30,5);
Insert into ADMIN.INSUMO (INSUMO_ID,NOMBRE_INSUMO,UNIDAD_MEDIDA,STOCK_ACTUAL,STOCK_MINIMO) values (3,'Maiz Morado','kg',15,3);
REM INSERTING into ADMIN.MOVIMIENTO_INVENTARIO
SET DEFINE OFF;
REM INSERTING into ADMIN.PRODUCTO
SET DEFINE OFF;
Insert into ADMIN.PRODUCTO (PRODUCTO_ID,NOMBRE_PRODUCTO,CATEGORIA_ID,PRECIO,DISPONIBLE) values (1,'Causa Limeña',1,18,'S');
Insert into ADMIN.PRODUCTO (PRODUCTO_ID,NOMBRE_PRODUCTO,CATEGORIA_ID,PRECIO,DISPONIBLE) values (2,'Lomo Saltado',2,25.5,'S');
Insert into ADMIN.PRODUCTO (PRODUCTO_ID,NOMBRE_PRODUCTO,CATEGORIA_ID,PRECIO,DISPONIBLE) values (3,'Chicha Morada',3,12,'S');
Insert into ADMIN.PRODUCTO (PRODUCTO_ID,NOMBRE_PRODUCTO,CATEGORIA_ID,PRECIO,DISPONIBLE) values (4,'Aji de Gallina',2,35,'S');
REM INSERTING into ADMIN.PRODUCTO_INSUMO
SET DEFINE OFF;
Insert into ADMIN.PRODUCTO_INSUMO (PRODUCTO_ID,INSUMO_ID,CANTIDAD_REQUERIDA) values (1,1,0.3);
Insert into ADMIN.PRODUCTO_INSUMO (PRODUCTO_ID,INSUMO_ID,CANTIDAD_REQUERIDA) values (2,2,0.25);
Insert into ADMIN.PRODUCTO_INSUMO (PRODUCTO_ID,INSUMO_ID,CANTIDAD_REQUERIDA) values (3,3,0.1);
REM INSERTING into ADMIN.SUCURSAL
SET DEFINE OFF;
Insert into ADMIN.SUCURSAL (SUCURSAL_ID,NOMBRE,DIRECCION,CIUDAD,TELEFONO) values (1,'Sede Miraflores','Av. Larco 123','Lima','014567890');
Insert into ADMIN.SUCURSAL (SUCURSAL_ID,NOMBRE,DIRECCION,CIUDAD,TELEFONO) values (2,'Sede San Borja','Av. Aviación 456','Lima','014567891');
--------------------------------------------------------
--  DDL for Index PK_PRODUCTO_INSUMO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_PRODUCTO_INSUMO" ON "ADMIN"."PRODUCTO_INSUMO" ("PRODUCTO_ID", "INSUMO_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Procedure SP_REGISTRAR_SALIDA_INSUMO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN"."SP_REGISTRAR_SALIDA_INSUMO" (
    p_insumo_id     IN NUMBER,
    p_sucursal_id   IN NUMBER,
    p_cantidad      IN NUMBER,
    p_motivo        IN VARCHAR2
) AS
    v_stock_actual NUMBER;
    v_stock_minimo NUMBER;
BEGIN
    INSERT INTO movimiento_inventario (insumo_id, sucursal_id, tipo_movimiento, cantidad, motivo)
    VALUES (p_insumo_id, p_sucursal_id, 'SALIDA', p_cantidad, p_motivo);

    UPDATE insumo
       SET stock_actual = stock_actual - p_cantidad
     WHERE insumo_id = p_insumo_id
    RETURNING stock_actual, stock_minimo INTO v_stock_actual, v_stock_minimo;

    IF v_stock_actual <= v_stock_minimo THEN
        DBMS_OUTPUT.PUT_LINE('ALERTA: Insumo ' || p_insumo_id || ' por debajo del stock mínimo.');
    END IF;

    COMMIT;
END sp_registrar_salida_insumo;

/

  GRANT EXECUTE ON "ADMIN"."SP_REGISTRAR_SALIDA_INSUMO" TO "ROL_COCINERO_ORA";
--------------------------------------------------------
--  DDL for Function FN_DISPONIBILIDAD_PRODUCTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "ADMIN"."FN_DISPONIBILIDAD_PRODUCTO" (p_producto_id IN NUMBER)
RETURN VARCHAR2 AS
    v_faltantes NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_faltantes
    FROM producto_insumo pi
    JOIN insumo i ON i.insumo_id = pi.insumo_id
    WHERE pi.producto_id = p_producto_id
      AND i.stock_actual < pi.cantidad_requerida;

    IF v_faltantes > 0 THEN
        RETURN 'NO_DISPONIBLE';
    ELSE
        RETURN 'DISPONIBLE';
    END IF;
END fn_disponibilidad_producto;

/
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CATEGORIA" MODIFY ("CATEGORIA_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CATEGORIA" MODIFY ("NOMBRE_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CATEGORIA" ADD PRIMARY KEY ("CATEGORIA_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."CATEGORIA" ADD UNIQUE ("NOMBRE_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HORARIO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."HORARIO" MODIFY ("HORARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."HORARIO" MODIFY ("EMPLEADO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."HORARIO" MODIFY ("DIA_SEMANA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."HORARIO" MODIFY ("HORA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."HORARIO" MODIFY ("HORA_FIN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."HORARIO" ADD PRIMARY KEY ("HORARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PRODUCTO" MODIFY ("PRODUCTO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PRODUCTO" MODIFY ("NOMBRE_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PRODUCTO" MODIFY ("CATEGORIA_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PRODUCTO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PRODUCTO" ADD CHECK (disponible IN ('S','N')) ENABLE;
  ALTER TABLE "ADMIN"."PRODUCTO" ADD PRIMARY KEY ("PRODUCTO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIMIENTO_INVENTARIO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" MODIFY ("MOVIMIENTO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" MODIFY ("INSUMO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" MODIFY ("SUCURSAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CHECK (tipo_movimiento IN ('ENTRADA','SALIDA')) ENABLE;
  ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD PRIMARY KEY ("MOVIMIENTO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUCURSAL
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SUCURSAL" MODIFY ("SUCURSAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SUCURSAL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SUCURSAL" ADD PRIMARY KEY ("SUCURSAL_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARGO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CARGO" MODIFY ("CARGO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CARGO" MODIFY ("NOMBRE_CARGO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CARGO" MODIFY ("SUELDO_BASE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CARGO" ADD PRIMARY KEY ("CARGO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."CARGO" ADD UNIQUE ("NOMBRE_CARGO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EMPLEADO" MODIFY ("EMPLEADO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLEADO" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLEADO" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLEADO" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLEADO" MODIFY ("CARGO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLEADO" MODIFY ("SUCURSAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLEADO" MODIFY ("FECHA_CONTRATACION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLEADO" ADD CHECK (estado IN ('ACTIVO','INACTIVO')) ENABLE;
  ALTER TABLE "ADMIN"."EMPLEADO" ADD PRIMARY KEY ("EMPLEADO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "ADMIN"."EMPLEADO" ADD UNIQUE ("DNI")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSUMO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."INSUMO" MODIFY ("INSUMO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INSUMO" MODIFY ("NOMBRE_INSUMO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INSUMO" MODIFY ("UNIDAD_MEDIDA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INSUMO" ADD PRIMARY KEY ("INSUMO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO_INSUMO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PRODUCTO_INSUMO" MODIFY ("PRODUCTO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PRODUCTO_INSUMO" MODIFY ("INSUMO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PRODUCTO_INSUMO" MODIFY ("CANTIDAD_REQUERIDA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PRODUCTO_INSUMO" ADD CONSTRAINT "PK_PRODUCTO_INSUMO" PRIMARY KEY ("PRODUCTO_ID", "INSUMO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASISTENCIA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ASISTENCIA" MODIFY ("ASISTENCIA_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ASISTENCIA" MODIFY ("EMPLEADO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ASISTENCIA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ASISTENCIA" ADD PRIMARY KEY ("ASISTENCIA_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASISTENCIA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ASISTENCIA" ADD FOREIGN KEY ("EMPLEADO_ID")
	  REFERENCES "ADMIN"."EMPLEADO" ("EMPLEADO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EMPLEADO" ADD FOREIGN KEY ("CARGO_ID")
	  REFERENCES "ADMIN"."CARGO" ("CARGO_ID") ENABLE;
  ALTER TABLE "ADMIN"."EMPLEADO" ADD FOREIGN KEY ("SUCURSAL_ID")
	  REFERENCES "ADMIN"."SUCURSAL" ("SUCURSAL_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HORARIO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."HORARIO" ADD FOREIGN KEY ("EMPLEADO_ID")
	  REFERENCES "ADMIN"."EMPLEADO" ("EMPLEADO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIMIENTO_INVENTARIO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD FOREIGN KEY ("INSUMO_ID")
	  REFERENCES "ADMIN"."INSUMO" ("INSUMO_ID") ENABLE;
  ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD FOREIGN KEY ("SUCURSAL_ID")
	  REFERENCES "ADMIN"."SUCURSAL" ("SUCURSAL_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PRODUCTO" ADD FOREIGN KEY ("CATEGORIA_ID")
	  REFERENCES "ADMIN"."CATEGORIA" ("CATEGORIA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO_INSUMO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PRODUCTO_INSUMO" ADD FOREIGN KEY ("PRODUCTO_ID")
	  REFERENCES "ADMIN"."PRODUCTO" ("PRODUCTO_ID") ENABLE;
  ALTER TABLE "ADMIN"."PRODUCTO_INSUMO" ADD FOREIGN KEY ("INSUMO_ID")
	  REFERENCES "ADMIN"."INSUMO" ("INSUMO_ID") ENABLE;
